server:
  port: 9090

eureka:
  client:
    serviceUrl:
      defaultZone: http://test-eureka-service.cfapps.io/eureka/
      #defaultZone: http://localhost:8761/eureka/

zuul:
  #Service will be mapped under the /api URI
  prefix: /api
#  Uncomment to disable auto-registering all services read from Eureka
#  ignoredServices: '*'
  routes:
    test:
      path: /redirect/**
      url: http://google.com
    user-list:
      path: /user/**
      url: http://test-user-lbcb.cfapps.io/user
    customer-by-address:
      path: /customer-by-address/**
      url: http://localhost:9098
    customer-by-service:
      path: /customer-by-service/**
      serviceId: CUSTOMER-SERVICE
    static:
      path: /static/**

spring:
  application:
    name: test-zuul-service